import type { RouteResult, SuggestedBreak } from "@/types/route";
import type { CostBreakdown, ItineraryDay } from "@/types/trip";
import { formatDuration } from "@/lib/costCalc";

function formatJPYPlain(amount: number): string {
  return `¥${amount.toLocaleString("ja-JP")}`;
}

function padRight(str: string, len: number): string {
  return str.padEnd(len, " ");
}

export function buildTripSummaryText(params: {
  origin: string;
  destination: string;
  waypoints: string[];
  route: RouteResult;
  costBreakdown: CostBreakdown;
  suggestedBreaks: SuggestedBreak[];
  itinerary?: ItineraryDay[];
}): string {
  const { origin, destination, waypoints, route, costBreakdown, suggestedBreaks, itinerary } = params;

  const lines: string[] = [];

  lines.push("🏍️ Japan バイク Trip Planner — Trip Summary");
  lines.push("==========================================");
  lines.push("");

  // ROUTE
  lines.push("ROUTE");
  lines.push(`${padRight("Start:", 13)}${origin}`);
  lines.push(`${padRight("Destination:", 13)}${destination}`);
  if (waypoints.length > 0) {
    lines.push(`${padRight("Stops:", 13)}${waypoints.join(" → ")}`);
  }
  lines.push(`${padRight("Distance:", 13)}${route.distanceKm.toFixed(0)} km`);
  lines.push(`${padRight("Riding time:", 13)}${formatDuration(route.durationMinutes)}`);
  lines.push(
    `${padRight("Breaks:", 13)}${
      suggestedBreaks.length === 0
        ? "None needed"
        : `${suggestedBreaks.length} suggested stop${suggestedBreaks.length > 1 ? "s" : ""}`
    }`
  );
  lines.push("");

  // COST ESTIMATE
  lines.push("COST ESTIMATE");
  lines.push(`${padRight("Fuel:", 15)}${formatJPYPlain(costBreakdown.fuel)}`);
  lines.push(`${padRight("Tolls:", 15)}${formatJPYPlain(costBreakdown.tolls)}`);
  lines.push(`${padRight("Accommodation:", 15)}${formatJPYPlain(costBreakdown.accommodation)}`);
  lines.push(`${padRight("Total:", 15)}${formatJPYPlain(costBreakdown.total)}`);
  lines.push("");

  // SUGGESTED BREAKS
  if (suggestedBreaks.length > 0) {
    lines.push("SUGGESTED BREAKS");
    suggestedBreaks.forEach((brk, i) => {
      lines.push(
        `☕ Break ${i + 1} — after ${formatDuration(brk.timeIntoRideMinutes)} (${brk.distanceIntoRouteKm} km in)`
      );
      lines.push(`   ${brk.note}`);
    });
    lines.push("");
  }

  // ITINERARY
  if (itinerary && itinerary.length > 0) {
    lines.push("ITINERARY");
    itinerary.forEach((day) => {
      lines.push(
        `Day ${day.day} — ${day.title}`
      );
      lines.push(
        `  Route: ${day.startLocation} → ${day.endLocation} | ${day.distanceKm} km | ${formatDuration(day.ridingTimeMinutes)}`
      );
      if (day.keyStops.length > 0) {
        lines.push(`  Stops: ${day.keyStops.join(", ")}`);
      }
      lines.push(
        `  Stay:  ${day.accommodation.name} (${day.accommodation.type})`
      );
      if (day.seasonalWarning) {
        lines.push(`  ⚠️  ${day.seasonalWarning}`);
      }
      lines.push("");
    });
  }

  lines.push("--");
  lines.push("Generated by Japan バイク Trip Planner");

  return lines.join("\n");
}
